import { User } from '../../types';

export const userData: User = {
	imageUrl:
		'https://s3-alpha-sig.figma.com/img/a504/ffb1/140fd5d4bfde22e928351d187bbf84e0?Expires=1710720000&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=PhlMUmd2Wvz6MgLsF61IhR9ehJeeRRBJoUrjFkS06zW-~MXtTOKxcAuu8wMm0VwM~mlWYtk3~Gowabl0i-ORbXWcnngh99JvUCdmqV6~51x7Oz3wtlwe5u-IsQ1fByD-DEojwTvu8xzMdX5LYYEQT5JL5CO6atqPrF5keBE8D5P1rTaVEK1smVBvKGmwBTQFdNe0OmW~6hiES9Q0hiipjaw1zm-AIJgCxd375uDKXrykrD8fK1zihOUxRMEVMQE7a4UReR3nZUa-5i8UlZtKNX6HkZqJeUqR3bsOi7dOIt4OTudzUtnQ6ORMoGLngD2kY8gGwD6gpqf29dZSr2UnsQ__',
	nickname: 'Minji_03',
	userName: '김민지',
	isUserNamePublic: true,
	interest: '프론트엔드',
	introduction: '복잡한 문제를 단순하게 바라보는 것을 즐깁니다:-)',
	aboutMe: `안녕하세요. 저는 성장을 꿈꾸는 김민지입니다!\n현재 ~한 개발을 하며 ~를 공부하고 있습니다.`,
	universityEmail: {
		content: 'Minji_03@kw.ac.kr',
		isPublic: true,
		isDefault: true,
	},
	phone: {
		content: '010-8888-8888',
		isPublic: true,
	},
	university: '광운대학교 서울캠퍼스',
	department: '소프트웨어학부',
	maxGpa: '4.5',
	gpa: '4.15',
	year: '2019',
	skills: [
		{ id: '1', name: 'Node.js' },
		{ id: '1', name: 'Figma' },
		{ id: '1', name: 'TypeScript' },
		{ id: '1', name: 'React' },
		{ id: '1', name: 'NextJs' },
	],
	awards: [
		{
			title: '2022 공공데이터 활용 공모전',
			startDate: '2022.06',
			endDate: '2022.08',
			description: '참여',
		},
		{
			title: '2022 공공데이터 활용 공모전',
			startDate: '2022.06',
			endDate: '2022.08',
			description: '참여',
		},
	],
	links: [
		{
			url: 'https://github.com/Minji_03',
			description: '깃허브',
		},
	],
	portfolios: [
		{
			id: '1',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: true,
			pinOrder: '1',
		},
		{
			id: '2',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: true,
			pinOrder: '2',
		},
		{
			id: '3',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: true,
			pinOrder: '3',
		},
		{
			id: '4',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: false,
			pinOrder: '0',
		},
		{
			id: '5',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: true,
			pinOrder: '4',
		},
		{
			id: '6',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: false,
			pinOrder: '0',
		},
		{
			id: '7',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: false,
			pinOrder: '0',
		},
		{
			id: '8',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: true,
			pinOrder: '5',
		},
		{
			id: '9',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: true,
			pinOrder: '6',
		},
		{
			id: '10',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: false,
			pinOrder: '0',
		},
		{
			id: '11',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: false,
			pinOrder: '0',
		},
		{
			id: '12',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: false,
			pinOrder: '0',
		},
		{
			id: '13',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: false,
			pinOrder: '0',
		},
		{
			id: '14',
			mainImageUrl: '',
			title: '[Meeteam] 대학생 포트폴리오 기반 구인 플랫폼',
			field: '개발',
			role: '프론트엔드',
			pinned: false,
			pinOrder: '0',
		},
	],
};
