interface ImportMeta {
	env: {
		VITE_BASE_URL: string;
		VITE_ACCESS_TOKEN_KEY: string;
		VITE_NAVER_CLIENT_ID: string;
		VITE_NAVER_STATE: string;
		VITE_NAVER_CALLBACK_URL: string;
		VITE_PLATFORM_ID: string;
		VITE_SECURE_LOCAL_STORAGE_HASH_KEY: string;
		VITE_SECURE_LOCAL_STORAGE_PLATFORM_ID: string;
	};
}
